name: lanla_flutter
description: LanLa Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.63+338

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.permission_handler
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

environment:
  sdk: ">=2.18.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  persistent_bottom_nav_bar: any
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  dio: ^5.1.1
  extended_tabs: ^3.0.3
  cached_network_image: ^3.2.2
  card_swiper: ^2.0.4
  fijkplayer: ^0.10.1
  card_loading: ^0.2.2
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.1.0
  wechat_camera_picker: ^3.6.1
  wechat_assets_picker: ^8.1.3
  flutter_image_compress: ^1.0.0-nullsafety
  http: ^0.13.3
  flutter_datetime_picker: ^1.5.1
  #本地存储
  shared_preferences: ^2.0.15
  video_thumbnail: ^0.5.3
  logger: ^1.1.0
  path_provider: ^2.0.11
  mime_type: ^1.0.0
  geolocator: ^9.0.2
  share_plus: ^4.5.3
  country_picker: ^2.0.16
  firebase_core: ^1.24.0
  google_sign_in: ^5.4.2
  flustars: ^2.0.1
  fluttertoast: ^8.1.1
  flutter_facebook_auth: ^4.4.1+1
  firebase_crashlytics: ^2.9.0
  firebase_auth: ^3.11.2
  url_launcher: ^6.1.6
  flutter_chat_ui: ^1.6.5
  flutter_svg: ^1.1.6
  appsflyer_sdk: ^6.8.2
  permission_handler: ^10.2.0
  keyboard_actions: ^4.1.0
  event_bus: ^2.0.0
  photo_view: ^0.14.0
  package_info_plus: ^3.0.1
  device_info_plus: ^8.0.0
  webview_flutter: ^3.0.4
  flutter_sound: ^9.2.13
  audio_session: ^0.1.10
  circular_seek_bar: ^1.0.3+1
  firebase_core_platform_interface: 4.5.1
  firebase_analytics: ^9.3.8
  video_player: ^2.4.8
  google_maps_flutter: ^2.2.1
  video_compress: ^3.1.2
  firebase_messaging: ^13.1.0
  flutter_picker: ^2.0.5
  carousel_slider: ^4.1.1
  uni_links: ^0.5.1
  adjust_sdk: ^4.31.0
  in_app_purchase: ^3.1.1
  web_socket_channel: ^2.3.0
  image_gallery_saver: ^1.7.1
  syncfusion_flutter_charts: ^20.4.50
  flutter_oss_aliyun: ^6.2.3
  firebase_storage: ^10.3.11
  firebase_dynamic_links: ^4.3.11
  google_mobile_ads: ^2.4.0
  #  flutter_html: ^3.0.0-beta.2
  #  flutter_html: ^2.2.1
  vsc_quill_delta_to_html: ^1.0.3
  flutter_quill: ^7.1.16+1
  image_picker: ^0.8.9
  flutter_widget_from_html: ^ 0.9.1
  facebook_audience_network: ^1.0.1
  #  advertising_id: ^2.4.0
  unity_ads_plugin: ^0.3.8
  intl: ^0.17.0
  reorderables: ^0.6.0
  tcard: ^1.3.5
#  flutter_udid: ^2.0.1
#  extended_text_field: ^10.2.0

# 文件保存插件
#  firebase_messaging: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/logotwo.png
    - assets/images/xhs_logo.jpg
    - assets/images/bottom_plus.png
    - assets/images/add.png
    - assets/images/man.png
    - assets/images/yihuanzhuta.png
    - assets/images/woman.png
    - assets/images/xuanman.png
    - assets/images/xuanwoman.png
    - assets/images/facebooklogin.png
    - assets/images/applelogin.png
    - assets/images/googlelogin.png
    - assets/images/phonebottom.png
    - assets/images/shangjiantou.png
    - assets/images/xiajiantou.png
    - assets/images/bdphone.png
    - assets/images/bdapple.png
    - assets/images/bdfacebook.png
    - assets/images/bdgoogle.png
    - assets/images/weixuan.png
    - assets/images/jiahao.png
    - assets/images/wenhaots.png
    - assets/images/zhishiqi.png
    - assets/images/dwxiajt.png
    - assets/images/renztctp.png
    - assets/images/darenrzicon.png
    - assets/images/sahangpxh.png
    - assets/images/shangpbxh.png
    - assets/images/noshujua.png
    - assets/images/yzxuanz.png
    - assets/images/yzweixz.png
    - assets/images/chuangzuozbs.png
    - assets/images/renzhz.png
    - assets/images/renzhztwo.png
    - assets/images/hqheight.png
    - assets/images/tancthree.png
    - assets/images/renzhengbs1.png
    - assets/images/renzhengbs2.png
    - assets/images/renzhengbs3.png
    - assets/images/renzhengbs4.png
    - assets/images/xuanzhong.png
    - assets/images/Downarrow.png
    - assets/images/sousou_home.png
    - assets/images/bjt.png
    - assets/images/mytopBg.png
    - assets/images/huodongtc.png
    - assets/images/huodong2.png
    - assets/images/logo.png
    - assets/images/guanzhuta.png
    - assets/images/shouji.png
    - assets/images/facebookicon.png
    - assets/images/googicon.png
    - assets/images/apple.png
    - assets/images/gengduo.png
    - assets/images/noxin.png
    - assets/images/xin.png
    - assets/images/xuxian.png
    - assets/images/noGuanzhuBg.png
    - assets/images/shanginaiming.png
    - assets/images/shangpinpxhui.png
    - assets/images/lv1.png
    - assets/images/lv2.png
    - assets/images/lv3.png
    - assets/images/lv4.png
    - assets/images/lv5.png
    - assets/images/liwuqiang.png
    - assets/images/nodatashuju.png
    - assets/images/chatwo.png
    - assets/images/dengjitu.png
    - assets/images/gzlv1.png
    - assets/images/gzlv2.png
    - assets/images/gzlv3.png
    - assets/images/gzlv4.png
    - assets/images/gzlv5.png
    - assets/images/ZXLV1.png
    - assets/images/ZXLV2.png
    - assets/images/ZXLV3.png
    - assets/images/ZXLV4.png
    - assets/images/ZXLV5.png
    - assets/images/dengjishuoming.png
    - assets/images/duihuanlw.png
    - assets/images/qdtanc.png
    - assets/images/sigindg.png
    - assets/images/jinglibk.png
    - assets/images/sixin_new.png
    - assets/images/xiugaitoux.png
    - assets/images/noshou.png
    - assets/images/ceshitp.png
    - assets/images/tishiwh.png
    - assets/images/shou.png
    - assets/images/pinglun.png
    - assets/images/buxihuan.png
    - assets/images/Union.png
    - assets/images/buxihuanzz.png
    - assets/images/luwulist.png
    - assets/images/renwutp.png
    - assets/images/jubao.png
    - assets/images/fenxiang.png
    - assets/images/xiangce.png
    - assets/images/ceshi.png
    - assets/images/sixin.png
    - assets/images/reduce.png
    - assets/images/Tile.png
    - assets/images/faxiaoxi.png
    - assets/images/ltianjia.png
    - assets/images/paizhao.png
    - assets/images/shanchu.png
    - assets/images/Nocontent.png
    - assets/images/nofabubg.png
    - assets/images/noShouCangbg.png
    - assets/images/shitan.png
    - assets/images/shiguanzhu.png
    - assets/images/guanzhusahng.png
    - assets/images/noZanguobg.png
    - assets/images/zhanheshou.png
    - assets/images/xinguanzhu.png
    - assets/images/txzhanwei.png
    - assets/images/LanLazhanwei.png
    - assets/images/zan@.png
    - assets/images/release.png
    - assets/images/zhanweitufont.png
    - assets/images/yqmbj.png
    - assets/icons/message.png
    - assets/images/user_defalut.png
    - assets/images/logothree.png
    - assets/images/bjtwo.png
    - assets/images/appletwo.png
    - assets/images/googicontwo.png
    - assets/images/facebookicontwo.png
    - assets/images/shoujitwo.png
    - assets/images/biaoqing.png
    - assets/images/spshoucang.png
    - assets/images/pinglfc.png
    - assets/images/chaozan.png
    - assets/images/yibanpf.png
    - assets/images/tucao.png
    - assets/images/zaogao.png
    - assets/images/manyi.png
    - assets/images/laxintct.png
    - assets/images/cha.png
    - assets/images/chathree.png
    - assets/images/emailogin.png
    - assets/images/meiyou.png
    - assets/images/xiugai.png
    - assets/images/set.png
    - assets/images/xiaoxi.png
    - assets/images/dianzan.png
    - assets/images/shoucang.png
    - assets/images/nobeijing.png
    - assets/images/lyquxiao.png
    - assets/images/kaily.png
    - assets/images/luyin.png
    - assets/images/liwuicon.png
    - assets/images/lwzhanwt.png
    - assets/images/gengxtc.png
    - assets/images/topic/mytopbg.png
    - assets/images/yinbotwo.png
    - assets/images/jinghao.png
    - assets/images/hezuo.png
    - assets/images/haowutj.png
    - assets/images/yingjiangli.png
    - assets/images/spcommodity.png
    - assets/images/spcommoditytwo.png
    - assets/images/tianjia.png
    - assets/images/tjgz.png
    - assets/images/qxtjgz.png
    - assets/svg/longpvbj.svg
    - assets/svg/greenflame.svg
    - assets/images/drawer.png
    - assets/images/connectionShopClose.png
    - assets/images/default_head_image.png
    - assets/svg/xuanzhong.svg
    - assets/svg/weixuanzhong.svg
    - assets/svg/Vector.svg
    - assets/svg/zisize.svg
    - assets/svg/longtup.svg
    - assets/svg/facebookbd.svg
    - assets/svg/applebd.svg
    - assets/svg/googlebd.svg
    - assets/svg/emailbd.svg
    - assets/svg/Tile.svg
    - assets/svg/reduce.svg
    - assets/svg/chahaolong.svg
    - assets/svg/longship.svg
    - assets/svg/bi_drak.svg
    - assets/svg/huati_xin_sel.svg
    - assets/svg/huati_xin_nor.svg
    - assets/icons/home_plus.svg
    - assets/icons/logo_top_right.svg
    - assets/svg/guanzhu.svg
    - assets/svg/noguanzhu.svg
    - assets/svg/cha.svg
    - assets/svg/jubao.svg
    - assets/svg/lahei.svg
    - assets/svg/aboutus.svg
    - assets/svg/darenrzsvg.svg
    - assets/svg/caogao.svg
    - assets/svg/clear.svg
    - assets/svg/fankui.svg
    - assets/svg/guli.svg
    - assets/svg/shoppingxiao.svg
    - assets/svg/jia.svg
    - assets/svg/renwu.svg
    - assets/svg/tuichu.svg
    - assets/svg/yinsi.svg
    - assets/svg/xiajiantou.svg
    - assets/svg/jiangpinduihuan.svg
    - assets/icons/homePlusTwo.svg
    - assets/icons/lingdang.svg
    - assets/icons/sousuo.svg
    - assets/icons/home/publish.svg
    - assets/icons/publish/c.svg
    - assets/icons/publish/dingwei.svg
    - assets/icons/fanhui.svg
    - assets/icons/home/home.svg
    - assets/icons/home/home_active.svg
    - assets/icons/home/friend.svg
    - assets/icons/home/friend_active.svg
    - assets/icons/home/me.svg
    - assets/icons/home/me_active.svg
    - assets/icons/home/top.svg
    - assets/icons/home/top_active.svg
    - assets/svg/live.svg
    - assets/svg/zuojiantou.svg
    - assets/svg/yeslive.svg
    - assets/svg/shoucang.svg
    - assets/svg/noshoucang.svg
    - assets/svg/pinglun_new.svg
    - assets/svg/fenxiang.svg
    - assets/svg/kaishily.svg
    - assets/svg/zantly.svg
    - assets/svg/hfly.svg
    - assets/svg/jinghao.svg
    - assets/svg/yinpinbiaos.svg
    - assets/svg/duigou.svg
    - assets/svg/shanchu.svg
    - assets/svg/qianbao.svg
    - assets/svg/renwu.svg
    - assets/svg/xiugaiziliao.svg
    - assets/svg/yaoqing.svg
    - assets/svg/yanjing.svg
    - assets/svg/pingjia.svg
    - assets/svg/tuichu.svg
    - assets/svg/shezhi.svg
    - assets/svg/bi.svg
    - assets/svg/mic_new.svg
    - assets/svg/play_new.svg
    - assets/svg/heart_sel_new.svg
    - assets/svg/heart_nor_new.svg
    - assets/svg/whiteheart_nor_new.svg
    - assets/svg/xiangqu.svg
    - assets/svg/daka.svg
    - assets/svg/yinbo.svg
    - assets/svg/buxihuan.svg
    - assets/svg/youjiantou.svg
    - assets/svg/dingwei.svg
    - assets/svg/kfsj.svg
    - assets/svg/pinglun_heart_nor_new.svg
    - assets/svg/guanlianht.svg
    - assets/svg/xiazai.svg
    - assets/svg/xiaojt.svg
    - assets/images/home/publish.png
    - assets/images/nvIcon.png
    - assets/images/nanIcon.png
    - assets/images/dingwei.png
    - assets/images/fenxiang_mengban.png
    - assets/images/dianhuaxiao.png
    - assets/images/home/home.png
    - assets/images/home/home_active.png
    - assets/images/home/friend.png
    - assets/images/home/friend_active.png
    - assets/images/home/me.png
    - assets/images/home/me_active.png
    - assets/images/home/top.png
    - assets/images/home/top_active.png
    - assets/images/bfzanting.png
    - assets/images/bjfenxiang.png
    - assets/images/splash/lanla.png
    - assets/icons/publish/mac.svg
    - assets/icons/publish/topic.svg
    - assets/icons/publish/arrow.svg
    - assets/icons/fuji.svg
    - assets/icons/publish/bilibili.svg
    - assets/icons/publish/topic.png
    - assets/icons/publish/topic_little.png
    - assets/icons/publish/topic_button.svg
    - assets/icons/publish/x.png
    - assets/icons/publish/position.svg
    - assets/images/topic/collect1.png
    - assets/images/topic/collect2.png
    - assets/images/topic/topic_icon.png
    - assets/images/dianzanbj.png
    - assets/images/dlbeijingtu.png
    - assets/images/tuijian.png
    - assets/images/yiban.png
    - assets/images/buhao.png
    - assets/images/beiketwo.png
    - assets/images/xtxiaox.png
    - assets/images/jinbi.png
    - assets/images/beike.png
    - assets/images/dav.png
    - assets/images/jinbitc.png
    - assets/images/jinbixiang.png
    - assets/images/beikebj.png
    - assets/images/shouyibj.png
    - assets/images/beikexiang.png
    - assets/images/shouyixiang.png
    - assets/images/xianrenzhang.png
    - assets/images/appleicontwo.png

    - assets/images/zhongcao.png
    - assets/images/bjfanhui.png
    - assets/images/bjshouc.png

    - assets/images/zanting.png
    - assets/images/qianbao.png
    - assets/svg/zanting.svg
    - assets/images/infooutline.png

  #    - assets/font/Arslan.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PingFangBold
      fonts:
        - asset: assets/fonts/PingFangBold.ttf
    - family: PingFangRegular
      fonts:
        - asset: assets/fonts/PingFangSCRegular.ttf
    - family: DroidArabicKufi
      fonts:
        - asset: assets/fonts/Droid Arabic Kufi.ttf
    - family: DroidArabicKufiBold
      fonts:
        - asset: assets/fonts/Droid-Arabic-Kufi-Bold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#  fonts:
#    - family: Arslan
#      fonts:
#        - asset: assets/font/Arslan.ttf
#    - family: Khebrat
#      fonts:
#        - asset: assets/font/Khebrat.ttf
#          #style: italic
